-- MySQL Script generated by MySQL Workbench
-- Mon Jan 15 20:58:53 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Maaltijd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Maaltijd` (
  `idMaaltijd` INT NOT NULL,
  `idKok` INT NOT NULL,
  `naamMaaltijd` VARCHAR(45) NOT NULL,
  `maaltijdAfbeelding` VARCHAR(45) NULL,
  `datumMaaltijd` DATE NOT NULL,
  `maxEters` VARCHAR(45) NOT NULL,
  `maaltijdBeginTijd` DATETIME(6) NOT NULL,
  `maaltijdEindTijd` DATETIME(6) NOT NULL,
  `kosten` VARCHAR(45) NOT NULL,
  `beschrijving` VARCHAR(255) NULL,
  PRIMARY KEY (`idMaaltijd`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Studenten`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Studenten` (
  `idStudenten` INT NOT NULL,
  `naamStudent` VARCHAR(45) NOT NULL,
  `aantalMeeEters` VARCHAR(45) NULL,
  PRIMARY KEY (`idStudenten`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StudentMaaltijd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`StudentMaaltijd` (
  `idStudent` INT NOT NULL,
  `idMaaltijd` INT NOT NULL,
  PRIMARY KEY (`idStudent`, `idMaaltijd`),
  INDEX `FK_Maaltijd_idx` (`idMaaltijd` ASC),
  CONSTRAINT `FK_Maaltijd`
    FOREIGN KEY (`idMaaltijd`)
    REFERENCES `mydb`.`Maaltijd` (`idMaaltijd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Kok`
    FOREIGN KEY (`idStudent`)
    REFERENCES `mydb`.`Studenten` (`idStudenten`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kok`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Kok` (
  `idKok` INT NOT NULL,
  `idMaaltijd` INT NOT NULL,
  `naamKok` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idKok`),
  INDEX `FK_KokMaaltijd_idx` (`idMaaltijd` ASC),
  CONSTRAINT `FK_KokMaaltijd`
    FOREIGN KEY (`idMaaltijd`)
    REFERENCES `mydb`.`Maaltijd` (`idMaaltijd`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
