-- MySQL Script generated by MySQL Workbench
-- Tue Jan 16 14:55:01 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Maaltijd`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Maaltijd` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Maaltijd` (
  `idMaaltijd` INT NOT NULL AUTO_INCREMENT,
  `idKok` INT NOT NULL,
  `naamMaaltijd` VARCHAR(255) NOT NULL,
  `maaltijdAfbeelding` VARCHAR(255) NULL,
  `maxEters` INT NOT NULL,
  `maaltijdBeginTijd` DATETIME(6) NOT NULL,
  `maaltijdEindTijd` DATETIME(6) NOT NULL,
  `kosten` DECIMAL(2) NOT NULL,
  `beschrijving` VARCHAR(255) NULL,
  PRIMARY KEY (`idMaaltijd`, `idKok`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Student` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `idStudenten` INT NOT NULL AUTO_INCREMENT,
  `naamStudent` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `wachtwoord` VARCHAR(255) NOT NULL,
  `aantalMeeEters` INT NULL,
  PRIMARY KEY (`idStudenten`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StudentMaaltijd`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`StudentMaaltijd` ;

CREATE TABLE IF NOT EXISTS `mydb`.`StudentMaaltijd` (
  `idStudent` INT NOT NULL,
  `idMaaltijd` INT NOT NULL,
  PRIMARY KEY (`idStudent`, `idMaaltijd`),
  INDEX `FK_Maaltijd_idx` (`idMaaltijd` ASC),
  CONSTRAINT `FK_Maaltijd`
    FOREIGN KEY (`idMaaltijd`)
    REFERENCES `mydb`.`Maaltijd` (`idMaaltijd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Kok`
    FOREIGN KEY (`idStudent`)
    REFERENCES `mydb`.`Student` (`idStudenten`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MaaltijdKok`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MaaltijdKok` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MaaltijdKok` (
  `idKok` INT NOT NULL,
  `idStudent` INT NOT NULL,
  PRIMARY KEY (`idKok`),
  INDEX `FK_Kok_idx` (`idStudent` ASC),
  CONSTRAINT `FK_StudentKok`
    FOREIGN KEY (`idStudent`)
    REFERENCES `mydb`.`Student` (`idStudenten`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_MaaltijdKok`
    FOREIGN KEY (`idKok`)
    REFERENCES `mydb`.`Maaltijd` (`idKok`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
